// <auto-generated />
using LDTTeam.Authentication.Modules.GitHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LDTTeam.Authentication.Modules.GitHub.Data.Migrations
{
    [DbContext(typeof(GitHubDatabaseContext))]
    [Migration("20210716094401_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGitHubTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGitHubUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGithubTeamUser", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("DbGithubTeamUser");
                });

            modelBuilder.Entity("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGithubTeamUser", b =>
                {
                    b.HasOne("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGitHubTeam", "Team")
                        .WithMany("UserRelationships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGitHubUser", "User")
                        .WithMany("TeamRelationships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGitHubTeam", b =>
                {
                    b.Navigation("UserRelationships");
                });

            modelBuilder.Entity("LDTTeam.Authentication.Modules.GitHub.Data.Models.DbGitHubUser", b =>
                {
                    b.Navigation("TeamRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
