// <auto-generated />
using System;
using LDTTeam.Authentication.DiscordBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LDTTeam.Authentication.DiscordBot.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251216151705_Add server for role assignment")]
    partial class Addserverforroleassignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LDTTeam.Authentication.DiscordBot.Model.Data.AssignedReward", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reward")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Reward", "Type");

                    b.ToTable("AssignedRewards");
                });

            modelBuilder.Entity("LDTTeam.Authentication.DiscordBot.Model.Data.RoleRewards", b =>
                {
                    b.Property<string>("Reward")
                        .HasColumnType("text");

                    b.Property<decimal>("Role")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Server")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Reward", "Role");

                    b.ToTable("RoleRewards");
                });

            modelBuilder.Entity("LDTTeam.Authentication.DiscordBot.Model.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Snowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Snowflake")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
