// <auto-generated />
using System;
using LDTTeam.Authentication.RewardAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LDTTeam.Authentication.RewardAPI.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251223120841_Properly configure the PK of the ProviderLogin table.")]
    partial class ProperlyconfigurethePKoftheProviderLogintable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LDTTeam.Authentication.RewardAPI.Model.Data.AssignedReward", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reward")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Reward", "Type");

                    b.HasIndex("Reward", "Type")
                        .IsUnique();

                    b.ToTable("AssignedRewards");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardAPI.Model.Data.ProviderLogin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Provider", "ProviderUserId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardAPI.Model.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardAPI.Model.Data.AssignedReward", b =>
                {
                    b.HasOne("LDTTeam.Authentication.RewardAPI.Model.Data.User", "User")
                        .WithMany("Rewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardAPI.Model.Data.ProviderLogin", b =>
                {
                    b.HasOne("LDTTeam.Authentication.RewardAPI.Model.Data.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardAPI.Model.Data.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("Rewards");
                });
#pragma warning restore 612, 618
        }
    }
}
