// <auto-generated />
using System;
using LDTTeam.Authentication.PatreonApiUtils.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LDTTeam.Authentication.PatreonApiUtils.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251218202855_Add AccountProvider enum handling")]
    partial class AddAccountProviderenumhandling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Membership", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGifted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastChargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastChargeSuccessful")
                        .HasColumnType("boolean");

                    b.Property<long>("LifetimeCents")
                        .HasColumnType("bigint");

                    b.HasKey("MembershipId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.PatreonTokenInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TokenInformation");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Reward", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGifted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LifetimeCents")
                        .HasColumnType("bigint");

                    b.HasKey("MembershipId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.RewardMembership", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.HasKey("MembershipId", "Tier");

                    b.ToTable("RewardMemberships");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.TierMembership", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.HasKey("MembershipId", "Tier");

                    b.ToTable("TierMemberships");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatreonId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.HasIndex("PatreonId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Reward", b =>
                {
                    b.HasOne("LDTTeam.Authentication.PatreonApiUtils.Model.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.RewardMembership", b =>
                {
                    b.HasOne("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Reward", "Reward")
                        .WithMany("Tiers")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.TierMembership", b =>
                {
                    b.HasOne("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Membership", "Membership")
                        .WithMany("Tiers")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.User", b =>
                {
                    b.HasOne("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Membership", null)
                        .WithOne("User")
                        .HasForeignKey("LDTTeam.Authentication.PatreonApiUtils.Model.Data.User", "MembershipId");
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Membership", b =>
                {
                    b.Navigation("Tiers");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("LDTTeam.Authentication.PatreonApiUtils.Model.Data.Reward", b =>
                {
                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
