// <auto-generated />
using System;
using LDTTeam.Authentication.RewardsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LDTTeam.Authentication.RewardsService.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251214130651_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LDTTeam.Authentication.RewardsService.Model.Data.UserLifetimeContributions", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("LifetimeContributions")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("LifeTimeContributions");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardsService.Model.Data.UserRewardAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Reward")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Type", "Reward");

                    b.ToTable("RewardAssignments");
                });

            modelBuilder.Entity("LDTTeam.Authentication.RewardsService.Model.Data.UserTierAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tier")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Tier");

                    b.ToTable("TierAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
